name: rick_and_morty_app
description: A Rick And Morty Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  rick_and_morty_api:
    git: https://github.com/Yash-Garg/RickandMorty-Dart-Wrapper.git
  injectable: ^2.3.0
  get_it: ^7.6.0
  auto_mappr_annotation: ^1.2.0
  shared_preferences: ^2.2.0

dependency_overrides:
  dio: ^5.0.0
  lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^7.0.8
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.0
  auto_mappr: ^1.7.0

flutter:
  uses-material-design: true
  shaders:
    - assets/warp_speed.glsl
    - assets/stars_background.glsl